# Generated by Django 4.0.4 on 2022-05-11 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtiApi', '0002_products_product_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='prooduct_price',
            field=models.FloatField(),
        ),
    ]
