# Generated by Django 4.0.4 on 2022-06-12 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtiApi', '0002_remove_products_supermarket_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='supermarket_price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
