# Generated by Django 4.0.4 on 2022-05-25 03:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dtiApi', '0004_alter_products_product_category_concern'),
    ]

    operations = [
        migrations.AddField(
            model_name='concern',
            name='publish_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
