# Generated by Django 4.0.4 on 2022-06-12 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtiApi', '0004_remove_concern_concern_adress'),
    ]

    operations = [
        migrations.AddField(
            model_name='concern',
            name='concern_adress',
            field=models.BooleanField(default=False),
        ),
    ]
