# Generated by Django 4.0.4 on 2022-06-12 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtiApi', '0005_concern_concern_adress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concern',
            name='publish_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
