# Generated by Django 4.0.4 on 2022-05-25 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtiApi', '0005_concern_publish_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_file', models.FileField(upload_to='pdf/')),
                ('publish_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
