# Generated by Django 4.0.4 on 2022-05-26 11:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dtiApi', '0006_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='publish_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
