# Generated by Django 4.0.4 on 2022-06-19 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtiApi', '0006_alter_concern_publish_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_category',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='ProductCategory',
        ),
    ]
