# Generated by Django 4.0.4 on 2022-06-26 11:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dtiApi', '0007_alter_products_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='as_of',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
