# Generated by Django 4.0.4 on 2022-06-27 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtiApi', '0008_products_as_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_srp',
            field=models.FloatField(default=12),
            preserve_default=False,
        ),
    ]
