# Generated by Django 4.0.4 on 2022-06-28 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtiApi', '0011_alter_products_product_srp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='product_category',
        ),
        migrations.AlterField(
            model_name='products',
            name='as_of',
            field=models.DateField(),
        ),
    ]
