# Generated by Django 4.0.4 on 2022-06-28 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dtiApi', '0012_remove_products_product_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='product_description',
        ),
    ]
